async function main() {
    
}

main().catch((error) => console.log(`An error occured: ${error}`));
